### ISSUE TITLE
Support mongodb?

### ISSUE THREAD

**Issue by conduongtong** [Skn0tt/prisma-erd#12]
I just tested this shema: 
```js
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id              String                 @id @default(auto()) @map("_id") @db.ObjectId
  name            String
}
```

It return error:
```
error: Error parsing attribute \"@default\": The function auto is not a known function.
```

Does this support mongo?
Sorry for my bad english, btw.

**Comment by Skn0tt** [comment]
I've tried updating the prisma engine that's used to parse the schema under the hood, but that doesn't work either. I don't think this will support MongoDB, then.
